### ISSUE TITLE
Fork > dotnet restore > fail

### ISSUE THREAD

**Issue by tebeco** [ElectronNET/Electron.NET#29] opened 2017-11-03 16:40 UTC
Hi,

I Just tried yo fork and restore for a PR but here it how it went :

```
C:\Workspace\GitHub\TeBeCo>git clone https://github.com/tebeco/Electron.NET
Cloning into 'Electron.NET'...
remote: Counting objects: 1442, done.
remote: Compressing objects: 100% (315/315), done.
remote: Total 1442 (delta 268), reused 383 (delta 170), pack-reused 924
Receiving objects: 100% (1442/1442), 3.40 MiB | 4.55 MiB/s, done.
Resolving deltas: 100% (836/836), done.

C:\Workspace\GitHub\TeBeCo>cd Electron.NET
C:\Workspace\GitHub\TeBeCo\Electron.NET>code-insiders .
C:\Workspace\GitHub\TeBeCo\Electron.NET>dotnet restore
  Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj...
  Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\ElectronNET.CLI.csproj...
  Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj...
  Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj...
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\obj\ElectronNET.CLI.csproj.nuget.g.props.
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\obj\ElectronNET.CLI.csproj.nuget.g.targets.
  Restore completed in 214.71 ms for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\ElectronNET.CLI.csproj.
  Restore completed in 253.32 ms for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj.
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\obj\ElectronNET.API.csproj.nuget.g.props.
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\obj\ElectronNET.API.csproj.nuget.g.targets.
  Restore completed in 1.1 sec for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj.
C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj : error NU1102: Unable to find package ElectronNET.API with version (>= 1.0.0)\r [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.sln]
C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 0.0.5 ]\r [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.sln]
C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj : error NU1102:   - Found 0 version(s) in LocalDev [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.sln]
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\obj\ElectronNET.WebApp.csproj.nuget.g.props.
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\obj\ElectronNET.WebApp.csproj.nuget.g.targets.
  Restore failed in 2.01 sec for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj.
```

ElectronNET.WebApp.csproj : error NU1102: Unable to find package ElectronNET.API with version (>= 1.0.0)\r [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.sln]
ElectronNET.WebApp.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 0.0.5 ]\r [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.sln]
ElectronNET.WebApp.csproj : error NU1102:   - Found 0 version(s) in LocalDev [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.sln]

**Comment by tebeco** [comment] 2017-11-03 16:43
I Also tried nuget CLI 4.1.0.2450


```
C:\Workspace\GitHub\TeBeCo\Electron.NET>nuget restore
MSBuild auto-detection: using msbuild version '15.4.8.50001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
WARNING: Project file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.Host\ cannot be found.
Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj...
Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj...
Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj...
Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\ElectronNET.CLI.csproj...
  CACHE https://api.nuget.org/v3-flatcontainer/electronnet.cli/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/electronnet.cli/0.0.5/electronnet.cli.0.0.5.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/electronnet.api/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegeneration.design/index.json
Committing restore...
Committing restore...
Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\obj\ElectronNET.CLI.csproj.nuget.g.props.
Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\obj\ElectronNET.CLI.csproj.nuget.g.targets.
Restore completed in 414.73 ms for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj.
Writing lock file to disk. Path: C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\obj\project.assets.json
Restore completed in 415.15 ms for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\ElectronNET.CLI.csproj.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegeneration.design/index.json 499ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegeneration.design/2.0.0/microsoft.visualstudio.web.codegeneration.design.2.0.0.nupkg
Package Microsoft.AspNetCore.Hosting.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Hosting.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more packages are incompatible with .NETCoreApp,Version=v2.0.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegeneration.design/2.0.0/microsoft.visualstudio.web.codegeneration.design.2.0.0.nupkg 448ms
Committing restore...
Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\obj\ElectronNET.API.csproj.nuget.g.props.
  GET https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegenerators.mvc/index.json
Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\obj\ElectronNET.API.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\obj\project.assets.json
Restore failed in 1.31 sec for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj.
  OK https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegenerators.mvc/index.json 468ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegenerators.mvc/2.0.0/microsoft.visualstudio.web.codegenerators.mvc.2.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegenerators.mvc/2.0.0/microsoft.visualstudio.web.codegenerators.mvc.2.0.0.nupkg 440ms
Installing Microsoft.VisualStudio.Web.CodeGenerators.Mvc 2.0.0.
Installing Microsoft.VisualStudio.Web.CodeGeneration.Design 2.0.0.
Unable to resolve 'ElectronNET.API (>= 1.0.0)' for '.NETCoreApp,Version=v2.0'.
Unable to resolve 'ElectronNET.API (>= 1.0.0)' for '.NETCoreApp,Version=v2.0 (win10-x64)'.
Committing restore...
Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\obj\ElectronNET.WebApp.csproj.nuget.g.props.
Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\obj\ElectronNET.WebApp.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\obj\project.assets.json
Restore failed in 2.54 sec for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj.

Errors in C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj
    Package Microsoft.AspNetCore.Hosting.Abstractions 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Hosting.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
    One or more packages are incompatible with .NETCoreApp,Version=v2.0.

Errors in C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj
    Unable to resolve 'ElectronNET.API (>= 1.0.0)' for '.NETCoreApp,Version=v2.0'.
    Unable to resolve 'ElectronNET.API (>= 1.0.0)' for '.NETCoreApp,Version=v2.0 (win10-x64)'.

NuGet Config files used:
    C:\Workspace\GitHub\TeBeCo\Electron.NET\NuGet.Config
    C:\Users\ahert\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Workspace\GitHub\TeBeCo\Electron.NET\artifacts

Installed:
    2 package(s) to C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj
```

**Comment by robertmuehsig** [comment] 2017-11-03 20:55
Ah - sorry: First guess would be that we referenced the "ElectronNET.WebApp" as a project reference instead of a NuGet reference like the CLI.

Maybe invoke buildAll.cmd the first time - this should build the projects in correct order.

But I will take a look - sorry for the inconvenience!

**Comment by tebeco** [comment] 2017-11-03 21:08
```
C:\Workspace\GitHub\TeBeCo\Electron.NET>buildAll.cmd

C:\Workspace\GitHub\TeBeCo\Electron.NET>echo "Start building Electron.NET dev stack..."
"Start building Electron.NET dev stack..."

C:\Workspace\GitHub\TeBeCo\Electron.NET>echo "Restore & Build API"
"Restore & Build API"

C:\Workspace\GitHub\TeBeCo\Electron.NET>cd ElectronNet.API

C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API>dotnet restore
  Restore completed in 22.38 ms for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj.

C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API>dotnet build
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

WebHostBuilderExtensions.cs(1,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj]
WebHostBuilderExtensions.cs(17,56): error CS0246: The type or namespace name 'IWebHostBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj]
WebHostBuilderExtensions.cs(17,23): error CS0246: The type or namespace name 'IWebHostBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj]

Build FAILED.

WebHostBuilderExtensions.cs(1,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj]
WebHostBuilderExtensions.cs(17,56): error CS0246: The type or namespace name 'IWebHostBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj]
WebHostBuilderExtensions.cs(17,23): error CS0246: The type or namespace name 'IWebHostBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:01.82

```


the build seems to continue though
but as you can see ... there's errors anyway

**Comment by robertmuehsig** [comment] 2017-11-04 22:27
I added some notes, because I think it is just because of the LocalDev NuGet folder that is empty on your machine: https://github.com/ElectronNET/Electron.NET#working-with-this-repo

Does that help?

**Comment by tebeco** [comment] 2017-11-05 21:13
i still got error with buildall.cmd also it takes too much time to finish the build
when i just wanted a restore ;)
will retry with 0.6

**Comment by robertmuehsig** [comment] 2017-11-05 21:22
As an alternative: Use dotnet build in the API and CLI folder, this should make sure the NuGet packages are present in the LocalDev folder under /artifacts

**Comment by robertmuehsig** [comment] 2017-11-12 09:11
Still having issues?

**Comment by tebeco** [comment] 2017-11-12 10:52
yes but i did not pull from the repo this week (had no time at work)
also after discussing about dotnet-cli on “aspnetcore slack” someone gave me the proper syntax, still need to test it

**Comment by tebeco** [comment] 2017-11-12 10:58
again when using a CLI extension there should be no trick should be either
* in the path so dotnet muxer fond it to redirect arcs
* an exe you can run (but for debug it is hard guess the RID)
* a dll (netstandard) you execute (not run like i did) using the muxer that will run it on the current runtime/platform

**Comment by tebeco** [comment] 2017-11-14 12:41
@robertmuehsig #56

**Comment by robertmuehsig** [comment] 2017-11-14 21:53
PR merged (and I also enhanced the .sh for osx/linux builds). Can this issue be closed?

**Comment by tebeco** [comment] 2017-11-15 06:24
I had a build error in a controller yesterday (about an event delegate not having the good signature)

is that normal to see both build green and this error locally ?

**Comment by robertmuehsig** [comment] 2017-11-15 07:06
I noticed it yesterday too, but I couldn’t reproduce it and the builds are fine. Do you still get the build error with the most recent version? Maybe the Webapp has used an older API NuGet package and it was resolved after a dotnet restore

Von meinem iPhone gesendet

Am 15.11.2017 um 07:24 schrieb TeBeCo <notifications@github.com<mailto:notifications@github.com>>:


I had a build error in a controller yesterday (about an event delegate not having the good signature)

is that normal to see both build green and this error locally ?

**Comment by robertmuehsig** [comment] 2017-11-15 23:17
Ok - I could reproduce it: Root cause is, that Gregor enhanced the API and used the new code in the WebApp. You need to execute the devCleanup.cmd and do a dotnet restore on the WebApp so that NuGet picks the updated Electron.API dll.

I will close this issue now - the original error has been resolved - hope this is OK for you.

**Closed by robertmuehsig** 2017-11-15 23:17 UTC
Labels: bug
