### ISSUE TITLE
Build process for 8.31.1 no longer produces a self-contained app

### ISSUE THREAD

**Issue by robalexclark** [ElectronNET/Electron.NET#396] opened 2020-05-09 18:34 UTC
There was a change from version 7.30.2 to 8.31.1 to the file ElectronNET.CLI/Commands/BuildCommand.cs where --no-self-contained is now specified. 
Previously this was not specified so a self-contained app was produced, but this change means that the dotnet core runtime needs to be manually installed on all target machines. Is this by design?

If it is by design then could you allow --self-contained true/false option to be specified to electronize build please?

**Comment by ThuCommix** [comment] 2020-05-09 19:38
I think it would be better if we could specify the dotnet publish arguments by ourselfs.

**Comment by GregorBiswanger** [comment] 2020-05-09 20:33
That was an accident and will be fixed in the upcoming version 8.31.2.

@ThuCommix  A "no" self contained doesn't really make sense for a portable cross platform solution .. I would like to have it active by default ..

**Comment by GregorBiswanger** [comment] 2020-05-09 20:35
Duplicate of #387

**Closed by GregorBiswanger** 2020-05-09 20:35 UTC
Labels: bug
