### ISSUE TITLE
Custom startup Code

### ISSUE THREAD

**Issue by BickelLukas** [ElectronNET/Electron.NET#182] opened 2018-11-12 08:03 UTC
It would be great if we were able to customize the code that's used to start the electron (and consiquently the .net) app. For example, I would like to check for updates on startup using https://github.com/electron/update.electronjs.org 

That's not possible at the moment. 

**Proposal**: 
Provide the Electron.NET.Host as an npm package. That way users can just have their own main.js and import the package and call "electron.net.start()" (or something similar). This would then start the .net app and setup the socket. Maybe you could also return an instance to the socket so that users could even implement their own methods. 

That would also solve the problem with custom node modules. 

Let me know what you think. I would also be happy to work on it and submit a PR.

**Comment by GregorBiswanger** [comment] 2019-01-03 19:33
Duplicate of #43

**Closed by GregorBiswanger** 2019-01-03 19:33 UTC
