### ISSUE TITLE
BridgeConnector Reconnected causes loss of socket

### ISSUE THREAD

**Issue by thomvandevin** [ElectronNET/Electron.NET#393] opened 2020-05-06 15:57 UTC
I'm still encountering this bug with the result that my frontend doesnt react on events anymore after a reconnect.

My hypothesis is that this happens whenever there is a large cpu or ram load going on. Due to this the app-lifetime can vary from 1 minute to multiple days depending on what I'm doing with my pc.
The result however is that the user will have to manually end the app-task through the task manager since closing the app otherwise will leave the user with around 5 processes that dont close. (the app is unstartable due to that)

Like I said, it happens pretty randomly but my guess is resource loads due to other programs. There is one way to trigger this bug consistently though:
- I make sure I log all events I send from my core to the frontend. (any other stream of logs will also work)
- I make the app 'hang' by selecting a log forcing the program in an 'awaiting' state
- I wait around 2 minutes
- Then I unselect the console-logs to make the app continue
- There is a high-chance (if you wait long enough; always) that the Bridge Reconnected message shows up.
- After this the app is left in a state where the frontend javascript calls still work, however the app doesnt update anymore.

In this broken state I can still manually refresh the page to make the app show the latest data, however events through listeners dont work anymore.
For some extra context **I attached an url to a youtube video replicating this**, I can provide you with some extra details or logs if you want.

My current environment:
* Windows 10
* **Version**: ElectronNET API & CLI 8.31.1.0
* **Target**: .NET Core 3.1 + NodeJS v12.16.2

Let me know if you have any ideas/details,
Greeting,
Thom

[![ElectronNET Bridge Connector bug](https://img.youtube.com/vi/WQDjJ5YtbTw/0.jpg)](https://www.youtube.com/watch?v=WQDjJ5YtbTw)

**Comment by cdespinosaagmx** [comment] 2020-05-08 18:29
I same the same issue, did you fixed this?

**Comment by GregorBiswanger** [comment] 2020-05-09 20:56
Honestly, I have no idea why the problem can be. Normally everything is still supported with a reconnect. Socket.IO and .NET Core with the library we used (SocketIoClientDotNet) are unfortunately no longer being developed and we would have to find an alternative. @syedadeel2  is currently working on a prototype of how we could do completely without websockets. However, this will be hard work because we have to rewrite our whole core.

However, I would have an idea for a workaround. You would have to try this out for yourself. If the connection is lost, you can completely reload the app. You would have to tap this via HostHook. See the Electron.NET API demo app under "Execute your own TypeScript code". In an emergency, I can show you the possible code. But would take time for me now. That might not be prioritized according to the prototype for me.

https://github.com/ElectronNET/electron.net-api-demos

**Comment by cdespinosaagmx** [comment] 2020-05-18 20:12
Gregor, this issue that makes bridgeconnector reconnected only happends in Electron.Net version 8.31 +?, or this happens in all version of Electron.Net cuz i'm working on a project using this tool but i always lose connectivity and after that i cant do any operation... so if i go back to an old version it will be fixed?? I see my electronize build /win failed too it loses brigeconnector too.

**Comment by konstantingross** [comment] 2020-05-19 00:35
Every now and then I get the same problems. You can also reproduce it, if you check for updates in debugger (not deployed / packed). 

But just for fun I updated to the newest version of socket.io and everything work like a charm! I noticed that ElectronNET.Host has a mismatch in the version number: package.json has 2.1.2 but package-lock.json has 2.1.4 maybe that causes the problems?

**Comment by GregorBiswanger** [comment] 2020-05-19 16:59
If the latest Socket.IO version works without problems.. Then we can update it.. best try with the demo app if everything still works..

**Comment by cdespinosaagmx** [comment] 2020-05-21 14:40
I only have one question about it, i updated to versions 8.31.2+, When i run ElectronNet project, menu is not working, i try to click Edit, View, Window, Help and it is not showing the dropdown, or popup. I had to clean something or it is a bug??

**Comment by GregorBiswanger** [comment] 2020-05-21 15:00
@cdespinosaagmx please see #401

**Comment by GregorBiswanger** [comment] 2020-05-23 16:11
Updatet to socket.io 2.3.0 - publish with Electron.NET 9.31.1

if the problem persists, we can open the issue again

**Closed by GregorBiswanger** 2020-05-23 16:11 UTC
Labels: bug, help wanted

**Comment by konstantingross** [comment] 2020-05-24 01:17
I have run several tests and this time no connection was closed!  So it seems stable to me.

**Comment by thomvandevin** [comment] 2020-05-25 16:51
Hey,
Are there any particular files I need to setup or change to publish with socket.io 2.3.0 and ElectronNET 9.31.1?
