### ISSUE TITLE
Failed To open dropdown menu in navbar

### ISSUE THREAD

**Issue by nacktech** [ElectronNET/Electron.NET#397] opened 2020-05-10 20:46 UTC
# Failed To open dropdown menu in bootstrap navbar

## Versions:
=> ElectronNET.CLI Version: 7.30.2.0
=> .Net core 3.1 and node 13.11.0

## Target: 
Windows, 
Linux,
Mac

## details:
Hello I add a dropdown menu with bootstrap, when I test it in the browser it works normally, but when I open in the electronNET "browser" it just don't work

the code is:
```
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
```

**Comment by nacktech** [comment] 2020-05-13 19:55
UPDATE:
is not just the navbar, all the external javascript files doesn't load. I have test it like this

in java.js:
```
var hasfoundthefile = "IEIE";
function HasChange() {
    $("#Testing").text("This has change")
}
```

in index.razor:
```
<button onclick="HasChange()">Test external javascript file</button>
<p id="Testing">Something</p>
```

when i click the button it was supposed to change the text but it doesn't do anything
I have put the script tag in _Host.razor refering to this file
I have also test it puting the file in the host/bin/ and refering by the full path, but it still dosent work.
SOMEBODY HELP ME

**Comment by GregorBiswanger** [comment] 2020-05-13 19:59
please create a prototype that I can test locally

**Comment by GregorBiswanger** [comment] 2020-05-15 22:01
Duplicate of #400

**Closed by GregorBiswanger** 2020-05-15 22:01 UTC
Labels: bug

**Comment by nacktech** [comment] 2020-05-16 00:52
Thank you very much

**Comment by romuloteixeira** [comment] 2021-05-10 11:51
Hi,
I used this solution and worked for me.
[https://github.com/ElectronNET/Electron.NET/issues/329#issuecomment-546612899](url)

**Comment by litch0** [comment] 2021-05-10 11:55
Oh, I didn't thought about that. I totally makes sense, It would take from the root directly! thanks
