### ISSUE TITLE
the example doesn't work

### ISSUE THREAD

**Issue by PrestigeDevop** [ElectronNET/Electron.NET#720] opened 2022-09-02 15:13 UTC
is this clean template  ( clean code ) 
um.. I might need some help here is there 

![image](https://user-images.githubusercontent.com/85388342/188175529-d9284fbb-0954-456d-8ddc-48c6a5a83bb8.png)

what am I missing here ?

**Comment by PrestigeDevop** [comment] 2022-09-02 16:27
it seems that the packages aren't installed correctly , when I try to install them manually it failed with dotnet 2.0 doesn't exist ( this is the first time I see this ) , I deleted obj folder and localnugtpackage.json   it didn't help any idea , or working sample

**Comment by PrestigeDevop** [comment] 2022-09-03 11:17
update : when I try Electron API demo with 
![image](https://user-images.githubusercontent.com/85388342/188267910-a5a530e5-47ef-47dd-a4e4-daa2af8ee97e.png)
![image](https://user-images.githubusercontent.com/85388342/188267926-5d6feb0c-bc0a-4d02-b820-a0518eba5bdc.png)

**Comment by PrestigeDevop** [comment] 2022-09-03 11:26
```
F:\New folder\ElectronCORE>electronize start
Start Electron Desktop Application...
Arguments:

dotnet publish  -r win-x64 -c "Debug" --output "F:\New folder\ElectronCORE\obj\Host\bin" /p:PublishReadyToRun=false /p:PublishSingleFile=false /p:DisabledWarnings=true
MSBuild version 17.3.0-preview-22329-01+77c72dd0f for .NET
F:\New folder\ElectronCORE\ElectronNET.sln : Solution file error MSB4249: Unable to build website project "ElectronNET.Host". The ASP.NET compiler is only available on the .NET Framework version of MSBuild.


Error occurred during dotnet publish: 1
```

**Comment by PrestigeDevop** [comment] 2022-09-05 20:37
So it seems that I had to restrict dotnet sdk to v5 using globl.json also deleting Nuget package catch and performing 
https://github.com/dotnet/msbuild/issues/7940#issuecomment-1236172029

hmm now it seems that https://status.nuget.org/ has some issue 

![image](https://user-images.githubusercontent.com/85388342/188510424-5abbdd4a-3ccd-405d-b067-02f79159d8c2.png)

**Comment by PrestigeDevop** [comment] 2022-09-10 19:16
currently I'm using https://github.com/medhatelmasry/ElectronServerBlazorEf , however I couldn't enable  hot reload ..

**Comment by rtaylor72** [comment] 2022-11-01 18:37
I am also running into this same error:
dotnet publish  -r win-x64 -c "Debug" --output "....\Electron.NET-master\obj\Host\bin" /p:PublishReadyToRun=false /p:PublishSingleFile=false /p:DisabledWarnings=true
MSBuild version 17.4.0-preview-22470-08+6521b1591 for .NET
C:\_Source\Other\Electron.NET-master\Electron.NET-master\ElectronNET.sln : Solution file error MSB4249: Unable to build website project "ElectronNET.Host". The ASP.NET compiler is only available on the .NET Framework version of MSBuild.

The ElectronNET.Host project references .NET Framework 4.8 in the solution file, and I think is the cause of this issue. Adding a global.json file in the solution directory is not working.  Any help with this?

Thanks!

**Comment by GregorBiswanger** [comment] 2023-03-28 10:44
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Closed by GregorBiswanger** 2023-03-28 10:44 UTC
Labels: question
