### ISSUE TITLE
Electron.NET throw exception "Cannot find module"

### ISSUE THREAD

**Issue by Voljinlvlan** [ElectronNET/Electron.NET#215] opened 2019-02-08 03:38 UTC
Hello .
System 
Os: win8 32-bit
ASP.Net Core: 2.2
Electron.NET API: v 11
In tab Error List 
1.  NETSDK1061: The project was restored using Microsoft.NETCore.App version 2.2.1, but with current settings, version 2.2.0 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish. Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore. For more information, see https://aka.ms/dotnet-runtime-patch-selection.	ElectronDotNet	D:\Programs\ElectronDotNet\ElectronDotNet\ElectronDotNet.csproj	1	

2. NETSDK1061: The project was restored using Microsoft.AspNetCore.App version 2.2.1, but with current settings, version 2.2.0 would be used instead. To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish. Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore. For more information, see https://aka.ms/dotnet-runtime-patch-selection.	ElectronDotNet	D:\Programs\ElectronDotNet\ElectronDotNet\ElectronDotNet.csproj	1	
 

when i run command "electronize start"
and this is error popup after that command

![image](https://user-images.githubusercontent.com/47439235/52457664-a4fdf280-2b8d-11e9-90ac-ccf5251ab1ec.png)

**Comment by searus** [comment] 2019-02-27 04:57
I get the same

**Comment by Voljinlvlan** [comment] 2019-02-27 07:41
What is your window os @searus

**Comment by GregorBiswanger** [comment] 2019-05-16 01:27
Duplicate of #205

**Closed by GregorBiswanger** 2019-05-16 01:27 UTC
Labels: duplicate
