### ISSUE TITLE
MenuItems not working

### ISSUE THREAD

**Issue by cdespinosaagmx** [ElectronNET/Electron.NET#412] opened 2020-05-21 15:11 UTC
* **Version**: ElectronNET API & CLI 8.31.2 +

* **Target**: .NET Core 3.1 + NodeJS v12.16.2

Steps to Reproduce:

1. Run the application with VS 2019 Electron.Net App
2. Try to click menu items

Nothing is happening when i click menu items like Edit, View, Window, Help in the application, it is something that is not happening in version 8.31.1

**Comment by srameh** [comment] 2020-05-21 17:21
I am getting the same error after upgrading to ElectronNET API & CLI 8.31.2

**Comment by GregorBiswanger** [comment] 2020-05-21 18:38
duplicate of #401 

I suspect that with a more recent Electron version the rules have become a bit stricter... I will implement a workaround... or should it remain that way by default?

**Comment by GregorBiswanger** [comment] 2020-05-21 20:59
I add an workaround for Electron.NET 8.31.3 - if someone has forgotten that a submenu exists and the type has not been set, this is now done automatically in the background.

**Closed by GregorBiswanger** 2020-05-21 20:59 UTC
Labels: bug

**Comment by srameh** [comment] 2020-05-22 08:50
I added the submenu type and when I run it as "electronize start /watch" the menu works but when I build it it does not work. Any reason or workaround?
