### ISSUE TITLE
BuildAll.cmd expect dotnet-electronize to be in the PATH

### ISSUE THREAD

**Issue by tebeco** [ElectronNET/Electron.NET#45] opened 2017-11-06 21:13 UTC
To be a bit more specific :

### Clone the repo in a brand new folder
```
$\> buildAll.cmd
```

The output is :
```
"Start building Electron.NET dev stack..."
"Restore & Build API"
  Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj...
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\obj\ElectronNET.API.csproj.nuget.g.props.
  Restore completed in 417.03 ms for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\ElectronNET.API.csproj.
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  ElectronNET.API -> C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.API\bin\Debug\netcoreapp2.0\ElectronNET.API.dll
  Successfully created package 'C:\Workspace\GitHub\TeBeCo\Electron.NET\artifacts\ElectronNET.API.1.0.0.nupkg'.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.86
"Restore & Build API"
  Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\ElectronNET.CLI.csproj...
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\obj\ElectronNET.CLI.csproj.nuget.g.props.
  Restore completed in 138.73 ms for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\ElectronNET.CLI.csproj.
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  ElectronNET.CLI -> C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\bin\Debug\netcoreapp2.0\dotnet-electronize.dll
  Successfully created package 'C:\Workspace\GitHub\TeBeCo\Electron.NET\artifacts\ElectronNET.CLI.1.0.0.nupkg'.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.91
"Restore & Build WebApp Demo"
  Restoring packages for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj...
  Restore completed in 18.86 ms for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj.
  Installing ElectronNET.API 1.0.0.
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\obj\ElectronNET.WebApp.csproj.nuget.g.props.
  Generating MSBuild file C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\obj\ElectronNET.WebApp.csproj.nuget.g.targets.
  Restore completed in 2.38 sec for C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj.
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  ElectronNET.WebApp -> C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\bin\Debug\netcoreapp2.0\ElectronNET.WebApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.53
"Invoke electronize build in WebApp Demo"
"-- win"
No executable found matching command "dotnet-electronize"
"-- linux"
No executable found matching command "dotnet-electronize"

C:\Workspace\GitHub\TeBeCo\Electron.NET>
```

I maybe wrong but
running `dotnet foobar` will try to find an executable named `dotnet-foobar` in the current folder (not sure about that one)
then in the PATH

here the build try to 
`dotnet electronize stuff`
and it feels logical that it fails since when developing this `dotnet` extension point we might not want it to be in the path.
but since we did build `dotnet-electronize` in the previos step it would be perfectly acceptable to run the actual `ElectronNet.Cli\bin\${Build_Config}\${Target_Runtime}\dotnet-electronize.exe build win`

### This is where this is interesting
i was trying to reproduce the CLI build

```
$\ElectronNet> cd ElectronNet.CLI
$\ElectronNet\ElectronNet.CLI> dotnet restore
$\ElectronNet\ElectronNet.CLI> dotnet buiild
$\ElectronNet\ElectronNet.CLI> cd bin\debug\netcoreapp2.0

$\ElectronNet\ElectronNet.CLI\bin\debug\netcoreapp2.0> ls -alh 
or
$\ElectronNet\ElectronNet.CLI\bin\debug\netcoreapp2.0> dir
```

output :

```
C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.CLI\bin\Debug\netcoreapp2.0>ls -alh
total 147K
drwxr-xr-x 1 ahert 197609    0 Nov  6 21:50 .
drwxr-xr-x 1 ahert 197609    0 Nov  6 21:50 ..
-rw-r--r-- 1 ahert 197609  486 Nov  6 21:50 dotnet-electronize.deps.json
-rwxr-xr-x 1 ahert 197609 131K Nov  6 21:50 dotnet-electronize.dll
-rw-r--r-- 1 ahert 197609 6.6K Nov  6 21:50 dotnet-electronize.pdb
-rw-r--r-- 1 ahert 197609  293 Nov  6 21:50 dotnet-electronize.runtimeconfig.dev.json
-rw-r--r-- 1 ahert 197609  154 Nov  6 21:50 dotnet-electronize.runtimeconfig.json
```

What is in CsProj ?

```
    <OutputType>exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyName>dotnet-electronize</AssemblyName>
```

see:
https://github.com/dotnet/cli/issues/6760

so either
* you need to specify each target RID 
* run it using `dotnet run ElectronNet.Cli\bin\${Build_Config}\${Target_Runtime}\dotnet-electronize.exe build win`

I guess the second one seems to be the best but so far i get this :
```
C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp>dotnet run "..\ElectronNET.WebApp\bin\Debug\netcoreapp2.0\ElectronNET.WebApp.dll" build win
Using launch settings from C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\Properties\launchSettings.json...

Unhandled Exception: System.FormatException: Unrecognized argument format: '..\ElectronNET.WebApp\bin\Debug\netcoreapp2.0\ElectronNET.WebApp.dll'.
   at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ElectronNET.WebApp.Program.BuildWebHost(String[] args) in C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\Program.cs:line 16
   at ElectronNET.WebApp.Program.Main(String[] args) in C:\Workspace\GitHub\TeBeCo\Electron.NET\ElectronNET.WebApp\Program.cs:line 11
```

it seems that the CLI tries to run the webapp .... WTF

**Comment by robertmuehsig** [comment] 2017-11-06 21:17
Gregor had the same problem when using it from the Visual Studio Powershell window. Could you try to use it in a "normal" cmd prompt? 

Otherwise the CLI is created like this example: https://blog.maartenballiauw.be/post/2017/04/10/extending-dotnet-cli-with-custom-tools.html

**Comment by tebeco** [comment] 2017-11-06 21:25
No luck i was already using `cmd` everywhere on this project

**Comment by robertmuehsig** [comment] 2017-11-06 21:31
Are you trying to add new stuff to the CLI? If yes: Be aware, that NuGet caches pretty aggressivly. You can use my command (devCleanup) or checkout our Wiki:
https://github.com/ElectronNET/Electron.NET/wiki

Another point: NuGet.org is currently down and I'm not sure if the dotnet cli extensions are "failure" tolerant. 

We just produce a CLI NuGet package, which is linked via the csproj - the loading and caching does dotnet/nuget for us. It's just a naming convention (dotnet-electronize).

**Comment by robertmuehsig** [comment] 2017-11-06 21:32
Oh - and we are not doing anything with the PATH. Our AppVeyor builds for example are very simple and I didn't need any setup for it.

**Comment by tebeco** [comment] 2017-11-06 21:35
the `buildAll.cmd` fail locally : `dotnet electronize` look for `dotnet-electronize` and there's no chance that it would fine it

i tried to fix it but so far with no sucess

**Comment by robertmuehsig** [comment] 2017-11-06 21:45
Nope - "dotnet-TOOLNAME" is a valid approach here. dotnet.exe searchs for a assembly name that has this pattern.

There are other examples out there with the same naming e.g. [Amazon does it this way](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Tools/Amazon.Lambda.Tools.csproj#L9) 

Our AppVeyor/TravisCI build does this all the time - it just invokes the buildAll.cmd/sh

It has nothing to do with PATH settings if you are using the .NET Core 2.0 SDK. Have you checked the wiki? Maybe you have an older cached version of the electronnet.cli package in the nuget cache.

**Comment by tebeco** [comment] 2017-11-06 21:48
but there's no exe, only a dll `dotnet-electronize.dll` because the `CLI.csproj` does not have RID

**Comment by robertmuehsig** [comment] 2017-11-06 22:01
This is by design - the CLI project itself will produce a .dll, which is packed as a NuGet package and is then consumed and run by dotnet.exe. This is nothing we invented, thats at least one way of doing it. 

Reference:

"As mentioned, tools are just portable console applications. You build tools as you would build any other console application. After you build it, you use the dotnet pack command to create a NuGet package (.nupkg file) that contains your code, information about its dependencies, and so on. You can give any name to the package, but the application inside, the actual tool binary, has to conform to the convention of dotnet-<command> in order for dotnet to be able to invoke it."

https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility#per-project-based-extensibility

Some other examples: https://github.com/dotnet/cli/tree/rel/1.0.1/TestAssets/TestPackages

The CLI extensions are "normal" dotnet core console apps and are meant to be run through dotnet.exe, just like a regular .NET Core Console app, see:

![image](https://user-images.githubusercontent.com/756703/32466184-58ab4bfe-c346-11e7-809b-12f64cbe87d1.png)

No .exe generated (at least if you don't do the RID stuff in it)

**Comment by tebeco** [comment] 2017-11-14 12:42
check #56

**Comment by robertmuehsig** [comment] 2017-11-14 12:46
Response in the PR.

**Comment by robertmuehsig** [comment] 2017-11-14 21:53
PR merged (and I also enhanced the .sh for osx/linux builds). Can this issue be closed?

**Comment by tebeco** [comment] 2017-11-15 06:21
totally forgot the other scripts do you want another PR so you could close this issue ?

**Comment by robertmuehsig** [comment] 2017-11-15 07:04
Do you mean the start.cmd/.sh? If yes: I think it might be good to avoid the NuGet cache problem locally

Von meinem iPhone gesendet

Am 15.11.2017 um 07:22 schrieb TeBeCo <notifications@github.com<mailto:notifications@github.com>>:


totally forgot the other scripts do you want another PR so you could close this issue ?

**Comment by robertmuehsig** [comment] 2017-11-15 23:15
I will close this one - the start.cmd/.sh file doesn't need it currently, because it skips the electronize start.

**Closed by robertmuehsig** 2017-11-15 23:15 UTC
Labels: question
