### ISSUE TITLE
Support for .net core 3 and Blazor 

### ISSUE THREAD

**Issue by srameh** [ElectronNET/Electron.NET#272] opened 2019-06-04 17:28 UTC
Do you guys have a plan for providing support for .net Core 3 and Blazor?
I believe building apps in .net Core 3 and Blazor will have a much better performance over MVC Angular.

**Comment by GregorBiswanger** [comment] 2019-06-04 18:01
Duplicate of #191

**Closed by GregorBiswanger** 2019-06-04 18:01 UTC
Labels: Feature
