### ISSUE TITLE
--no-self-contained flag is forced  upon build

### ISSUE THREAD

**Issue by kylethomas320** [ElectronNET/Electron.NET#398] opened 2020-05-11 12:59 UTC
* **Version**:  8.31.1

* **Target**: .NET Core 3.1

I recently upgraded from the previous electron v7 to v8.31.1 and noticed that `--no-self-contained` is put in the build command. I need my build to be a self contained file, as in previous versions of Electron .NET. Will this be fixed in a later version? As this is hardcoded in the c# CLI code, I can't force it to go to self-contained myself. See: https://github.com/ElectronNET/Electron.NET/commit/b6417d0718bca7a155b293175aa9afd50ce194d0#diff-3da8aff670c488206e99f7abe0c6f1bd.

Build command used:
`dotnet build /target win` 

Thanks for the support!

**Comment by GregorBiswanger** [comment] 2020-05-11 13:50
Duplicate of #387

**Closed by GregorBiswanger** 2020-05-11 13:50 UTC
Labels: bug
